/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Button;
import java.awt.Canvas;

/**
 *
 * @author estudiantes
 */
public class Vista extends javax.swing.JFrame {

    private Controlador control;
    private final Modelo sistema;

    public Vista(Modelo aThis) {
        sistema = aThis;
        initComponents();
        asignarEventos();
    }

    public Button getBtnAvance() {
        return btnAvance;
    }

    public Canvas getLienzo() {
        return lienzo;
    }

    public Controlador getControl() {
        if(control == null){
            control = new Controlador(this);
        }
        return control;
    }

    public Modelo getSistema() {
        return sistema;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo = new java.awt.Canvas();
        btnAvance = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(lienzo);
        lienzo.setBounds(10, 50, 440, 460);

        btnAvance.setLabel("button1");
        getContentPane().add(btnAvance);
        btnAvance.setBounds(470, 50, 65, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAvance;
    private java.awt.Canvas lienzo;
    // End of variables declaration//GEN-END:variables

    private void asignarEventos() {
        btnAvance.addActionListener(getControl());
    }
}
